"""create table Cadastro

Revision ID: 1cd8a02b6c08
Revises: 3c1e01a67e9a
Create Date: 2021-08-10 00:05:51.930278

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1cd8a02b6c08'
down_revision = '3c1e01a67e9a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cadastro', 'termo',
               existing_type=sa.VARCHAR(length=5),
               type_=sa.String(length=6),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cadastro', 'termo',
               existing_type=sa.String(length=6),
               type_=sa.VARCHAR(length=5),
               existing_nullable=False)
    # ### end Alembic commands ###
